---
title: "Efficient Matrix Multiplication in R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message="hide", results="hide"}
suppressMessages({
    library(microbenchmark)
    library(Rfast)
})
```


```{r, warning=FALSE, message=FALSE}
sourceCpp("../src/utils/test.cpp")
```

# matrices - small

```{r}
colsA <- 1000
colsB <- 2000
A <- matrix(rnorm(300*colsA), nrow = 300, ncol = colsA)
B <- matrix(rnorm(300*colsB), nrow = 300, ncol = colsB)
dim(A); dim(B)
```

## consistency

```{r, eval=FALSE}
res<-list(
`%*%`=t(A) %*% B,
crossprd=crossprod(A, B),
matmult=mat.mult(t(A), B),
eMM=eigenMatMult(t(A), B),
eMMM=eigenMapMatMult(t(A), B))

## all output the same matrix?
all.identical <- function(x) length(unique(x)) == 1
all.identical(res)
#> TRUE
```

# run times

```{r}
microbenchmark(list = list(
    `%*%`=t(A) %*% B,
    crossprd=crossprod(A, B),
    matmult=mat.mult(t(A), B),
    eMM=eigenMatMult(t(A), B),
    eMMM=eigenMapMatMult(t(A), B)) , times = 10)
```


# matrices - larger

```{r}
colsA <- 3000
colsB <- 5000
A <- matrix(rnorm(300*colsA), nrow = 300, ncol = colsA)
B <- matrix(rnorm(300*colsB), nrow = 300, ncol = colsB)
dim(A); dim(B)
```

## consistency

```{r, eval=FALSE}
res<-list(
`%*%`=t(A) %*% B,
crossprd=crossprod(A, B),
matmult=mat.mult(t(A), B),
eMM=eigenMatMult(t(A), B),
eMMM=eigenMapMatMult(t(A), B))

## all output the same matrix?
all.identical <- function(x) length(unique(x)) == 1
all.identical(res)
#> TRUE
```

# run times

```{r}
microbenchmark(list = list(
    `%*%`=t(A) %*% B,
    crossprd=crossprod(A, B),
    matmult=mat.mult(t(A), B),
    eMM=eigenMatMult(t(A), B),
    eMMM=eigenMapMatMult(t(A), B)) , times = 10)
```


